# Generated by Django 4.2.8 on 2023-12-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='age',
            field=models.IntegerField(),
        ),
    ]
