"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import environ



env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g)zz(@v&um)oc*pt2rn$p37hm=xpm2!*#)7haq==$kzaumv=98'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []





# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api.apps.ApiConfig',
    'ecom.apps.EcomConfig',
    'api2',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
SITE_ID=1
SOCIALACCOUNT_PROVIDERS = {
    'github':{
        'APP':{
            'client_id': 'a94b06b2fc807c699af0',
            'secret_key':'296bc86a9501d5fb49b03c0db45939a728023805',
        }
    }
}
ACCOUNT_EMAIL_VERIFICATION = None
LOGIN_REDIRECT_URL ='home'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'project.middleware.SimpleMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'




DATABASES = {
    'default': {
       'ENGINE': 'django.db.backends.postgresql_psycopg2',

        'NAME': 'vivek',

        'USER': 'postgres',

        'PASSWORD': 'Abhinav@51',

        'HOST': '127.0.0.1',

        'PORT': 5431,
    }
}

#cache
CACHE =  {
    "default" : {
        "BACKEND":"django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION":"absolute path for file",
    }
}
STATICFILES_DIRS = [
    BASE_DIR/'static',
]


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#account all auth

# ACCOUNT_ADAPTER = "allauth.account.adapter.DefaultAccountAdapter" 
# ACCOUNT_AUTHENTICATION_LOGIN_REDIRECTS = True
# ACCOUNT_AUTHENTICATION_METHOD = "username"
# ACCOUNT_CHANGE_EMAIL = False
# ACCOUNT_CONFIRM_EMAIL_ON_GET = False
# ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = None
# ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = "settings.LOGIN_URL"
# ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 2
# ACCOUNT_EMAIL_CONFIRMATION_HMAC = True
# ACCOUNT_EMAIL_REQUIRED  =False
# ACCOUNT_EMAIL_VERIFICATION  = "mandatory"
# ACCOUNT_EMAIL_SUBJECT_PREFIX = "[site]"
# ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http"
# ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5




# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
